### ISSUE TITLE
How to connect through a corporate proxy with authentication

### ISSUE THREAD

**Issue by SadarSSI** [vi/websocat#102]
Hello,

Is there a way to go through a corporate proxy with authentication before connecting to the server ? wss//xxxx

In my case, I am trying to do ssh to a server

W10 Client -> Coporate Proxy with authentication (Domain\User:Passwd@proxy:3129) -> websocat server (wss://myserver.com)-> ssh server (user@sshserver:10234)

Thanks for your help

**Comment by vi** [comment]
Can you use https://github.com/larryhou/connect-proxy to jump the authenticated proxy, getting to unencumbered 443 port?

**Comment by vi** [comment]
Approximate command line:

```
websocat -t - --ws-c-uri=wss://xxxx  --tls-domain=xxxx  ws-c:ssl-connect:cmd:'connect-proxy -H proxy:3129 xxxx 443'
```

You'll probably need to:

1. Obtain `connect-proxy` for Windows
2. Fiddle with command line to make it work on Windows
3. Set `connect-proxy`'s options and environment variables for authentication
4. Set actual URL and hostname for Websocket connection
5. Integrate that with a SSH client

**Comment by SadarSSI** [comment]
Ok, thank you very much for your answer
