### ISSUE TITLE
Large paste on Mac

### ISSUE THREAD

**Issue by georgefst** [vi/websocat#103]
Version 1.6.0

When trying to paste more than 1024 bytes in to `websocat -s` on MacOS Big Sur, something goes horribly wrong and I have to kill the process.

The first 1024 characters appear in the terminal, then I hear a few popping sounds and the terminal locks up.

**Comment by vi** [comment]
Is it related to #76?

Does working it around with `websocat -tE ws-l:127.0.0.1:1234 broadcast:threadedstdio:` instead of `-s` changes anything?

**Comment by georgefst** [comment]
> Is it related to #76?

Very possibly - it does look similar.

> Does working it around with websocat -tE ws-l:127.0.0.1:1234 broadcast:threadedstdio: instead of -s changes anything?

Unfortunately not. Is it worth trying to build from `HEAD` or is the only change just to make the default the same as passing those arguments?

**Comment by vi** [comment]
> Is it worth trying to build from HEAD or is the only change just to make the default the same as passing those arguments?

It is probably the case.

> Unfortunately not.

Does pasting it into, for example, `/bin/cat` work properly? What about pasting into `websocat  -b threadedstdio: mirror:` or `websocat  -b stdio: mirror:`? Which terminal emulator software do you use, does the problem stays the same with other emulator?

**Comment by georgefst** [comment]
Thanks for your time responding to this. Looks like it doesn't really have much to do with `websocat`...

> Does pasting it into, for example, /bin/cat work properly? What about pasting into websocat -b threadedstdio: mirror: or websocat -b stdio: mirror:?

No x3.

> Which terminal emulator software do you use, does the problem stays the same with other emulator?

Only tried the pre-installed terminal app so far.

Anyway, this seems to be a well-known issue, discussed e.g. [here](https://users.rust-lang.org/t/io-stdin-read-more-than-1024-characters-at-a-time/13223/5) and [here](https://unix.stackexchange.com/questions/204815/terminal-does-not-accept-pasted-or-typed-lines-of-more-than-1024-characters). What works is setting `STTY=-icanon`, as suggested in that second link.

**Comment by vi** [comment]
If it does not work with `cat` then it's probably not Websocat's business to deal with the problem.

Does the STTY workaround work for websocat?

Should using readline library help? Do other command-line programs for Mac typically handle such pastes (or automatically set STTY)?

**Comment by georgefst** [comment]
I'm unsure about other programs since I'm very new to the Mac ecosystem. But anyway, the `STTY` workaround works, so I'm back to being a happy user.
