### ISSUE TITLE
SystemD socket unit

### ISSUE THREAD

**Issue by cshorler** [vi/websocat#110]
Ultimately, I would like to have Nginx proxy_pass to a UNIX socket, where websocat is ready for the websocket connection.  With one other service I'm doing this on demand using systemd to spawn the handler service, it works well.  I guess this is a bit like an `inetd` setup, (except for systemd).

So far,  I have a systemd socket unit listening on a UNIX socket.  When a connection is detected it launches a service unit which invokes websocat.  This fails with the following message

```
# journalctl -u websocat.service
...
Mar 27 15:31:14 raspberrypi systemd[1]: Started websocat daemon.
Mar 27 15:31:14 raspberrypi websocat[2929]: websocat: Address already in use (os error 98)
Mar 27 15:31:14 raspberrypi websocat[2929]: websocat: error running
```

I believe this is because systemd has already created the socket to listen on it.

Is there a way to reuse the UNIX socket from systemd?

Things I tried so far:
`--unlink`
Reading `man systemd.socket` - under the `Accept=` section it says the socket must not be unlinked from the filesystem.

If I ignore this and use `--unlink` and set `UMask=0111` in the service unit file (for testing purposes), the connection is closed almost immediately.

local testing:
```
$ ssh -o "ProxyCommand=websocat -E --binary - ws-c:unix:/run/ws-ssh.sock" pi@localhost
websocat: Connection refused (os error 111)
websocat: error running
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

SystemD units

```
# cat /etc/systemd/system/websocat.socket 
[Unit]
Description=websocat sockets

[Socket]
#SocketMode=0666
ListenStream=/run/ws-ssh.sock

[Install]
WantedBy=sockets.target
```

```
# cat /etc/systemd/system/websocat.service 
[Unit]
Description=websocat daemon
Requires=websocat.socket
After=network.target

[Service]
# UMask=0111
# ExecStart=/usr/local/bin/websocat -E --unlink --binary l-ws-unix:/run/ws-ssh.sock tcp:127.0.0.1:22
ExecStart=/usr/local/bin/websocat -E --binary l-ws-unix:/run/ws-ssh.sock tcp:127.0.0.1:22

[Install]
WantedBy=multi-user.target
```

**Comment by vi** [comment]
Have you tried systemd's `Accept=yes` mode for socket, to make it spawn Websocat with an already connected socket?

**Comment by vi** [comment]
I also see the `--unlink` Websocat option missing from your unit file.

**Comment by vi** [comment]
Do you have any simple example (e.g. in C) of a service that is compatible with SystemD's `Accept=no` mode?

I'm not sure how is it supposed to work, as documentation says against unlinking the socket, but without unlinking one typically gets "Address already in use" error.

**Comment by vi** [comment]
Implemented new option: `--accept-from-fd`.

You can try it with [this pre-built file](https://github.com/vi/websocat/releases/download/v1.7.0/websocat_amd64-linux-static_accept).

Please try with `Accept=no` (i.e. the default) SystemD mode and this command line:

   /usr/local/bin/websocat -E --binary --accept-from-fd l-ws-unix:0 tcp:127.0.0.1:22

Report here please if it works, so I can document in in examples.

**Comment by cshorler** [comment]
Do you by chance have a quick way to build the arm binary?  (I was running it on arm)

**Comment by cshorler** [comment]
cupsd is doing it - for example:  https://github.com/apple/cups/blob/b27a49b8a06e65067b1ca950d39b34ae8b2fa008/scheduler/main.c#L1962

**Comment by vi** [comment]
https://github.com/vi/websocat/releases/download/v1.7.0/websocat_arm-linux-static_accept

**Comment by cshorler** [comment]
it works - slight modification to the command line
`man sd_listen_fds` 
shows 
`#define SD_LISTEN_FDS_START 3`

so I replaced `l-ws-unix:0` by `l-ws-unix:3`

**Comment by cshorler** [comment]
Thanks very much for the quick response!
