### ISSUE TITLE
Examples in document does not working

### ISSUE THREAD

**Issue by zbinlin** [vi/websocat#119]
>
>Example: Accept forwarded WebSocket connections from Nginx
>
>    umask 0000
>    websocat --unlink ws-l:unix-l:/tmp/wstest tcp:[::]:22
>      

This example in document, I try to run, but it not working. It shows `websocat: invalid IP address syntax`

**Comment by vi** [comment]
Updated the doc, now it contains `websocat --unlink -b -E ws-u:unix-l:/tmp/wstest tcp:[::]:22` - the main fix is `ws-u` instead of `ws-l`.

Does it work now?

**Comment by zbinlin** [comment]
It works.
Thanks!
