### ISSUE TITLE
Most recent release uses yanked crates

### ISSUE THREAD

**Issue by cinerea0** [vi/websocat#138]
Currently, the most recent release of websocat (v.1.8.0) relies on yanked versions of `arc-swap`, `crossbeam-deque`, `miow`, `net2`, and `socket2`. This makes it difficult to provide updates for websocat for some Linux distros. Could you please cut a new release with updated dependencies?

**Comment by vi** [comment]
Published v1.9.0. Is it OK? (I ran `cargo update`, but haven't specifically checked for crate yankedness).

**Comment by cinerea0** [comment]
Yep, that fixed it. Thank you!
