### ISSUE TITLE
Skip SSL/TLS verification?

### ISSUE THREAD

**Issue by plombardi89** [vi/websocat#14]
I was looking for something similar to `curl` `-k` option that lets you test a HTTPS endpoint even if you cannot verify the certificate. This is very useful for debug scenarios. Unfortunately I can't seem to find such an option if it exists.

**Comment by vi** [comment]
Not easy, it's not readily supported by websocat's dependencies (which are a bit outdated).

Fortunately, there is a workaround:

```
$ websocat -t -  ws-c:sh-c:'socat - ssl:174.129.224.73:443,verify=0' --ws-c-uri=wss://echo.websocket.org
dsaf
dsaf
dsafsadf
dsafsadf
```

**Comment by vi** [comment]
Have you succeed connecting to to wss:// without verification?

**Comment by plombardi89** [comment]
Haven't had a chance to try yet. Will give it a go this afternoon.

**Comment by vi** [comment]
Documented the workaround in [moreexamples.md](https://github.com/vi/websocat/blob/master/moreexamples.md).

**Comment by anfuse** [comment]
> $ websocat -t -  ws-c:sh-c:'socat - ssl:174.129.224.73:443,verify=0' --ws-c-uri=wss://echo.websocket.org

Unfortunately, this doesn't work in android, as socat for android doesn't support SSL. And there's no easy way to compile OpenSSL to use it instead of socat.
Is there an alternate solution?

**Comment by vi** [comment]
Is there openssl binary (with `s_client`) for Android?

**Comment by anfuse** [comment]
> Is there openssl executable (with `s_client`) for Android?

I didn't find any. There's no official port, and some unofficial come just as a library.

**Comment by anfuse** [comment]
> > Is there openssl executable (with `s_client`) for Android?
> 
> I didn't find any. There's no official executables, and some unofficial come only as a library.

**Comment by vi** [comment]
Built my own: https://android.stackexchange.com/a/203065/5387

Or do you need for x86?

**Comment by anfuse** [comment]
> Built my own: https://android.stackexchange.com/a/203065/5387

Thank you very much for your support.

Tested ARM version on Android 6, and it works fine as a replacement for `websocat -t tcp-l:127.0.0.1:1234 wss://echo.websocket.org`:

`websocat tcp-l:127.0.0.1:1234 sh-c:"websocat -v -t --ws-c-uri=wss://echo.websocket.org/ - ws-c:cmd:'openssl s_client -connect echo.websocket.org:443 -quiet'"`

(I don't think there's a better solution than running two instances of websocat in the example above.)

**Comment by vi** [comment]
Tried myself this:

    ./websocat -v -t tcp-l:127.0.0.1:1234 --ws-c-uri=wss://echo.websocket.org/ ws-c:exec:./openssl_android --exec-args s_client -connect echo.websocket.org:443 -quiet

It works, but only when I re-compiled websocat. Otherwise it fails with mysterious `called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: Other, message: "Is a directory"}`.

Is it the error you also experienced?

**Comment by vi** [comment]
Try this websocat: https://github.com/vi/websocat/releases/download/v1.1.0/websocat_nossl_arm-linux-static. Does it work without nesting?

**Comment by anfuse** [comment]
> Is it the error you also experienced?

I've been using this executable:

https://github.com/vi/websocat/releases/download/v1.1.0/websocat_arm-android

Sadly, I don't remember what error that was, and it's weird but I couldn't reproduce it. I might have had a typo in the command that time. Anyway, the non-nested command works consistently now.

> Try this websocat: https://github.com/vi/websocat/releases/download/v1.1.0/websocat_nossl_arm-linux-static. Does it work without nesting?

This one works fine too.
