### ISSUE TITLE
Max size on outbound messages?

### ISSUE THREAD

**Issue by spencerwilson** [vi/websocat#140]
Am running
```
$ websocat -v --protocol graphql-ws wss://example.com/ws
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::stdio_threaded_peer] get_stdio_peer (threaded)
[INFO  websocat::ws_client_peer] get_ws_client_peer
[INFO  websocat::ws_client_peer] Connected to ws
```
At this point if I begin typing, or if I paste a large message, my input ends/is truncated at 1024 characters and additional keypresses ring my terminal bell.

My objective is to send a text-mode message to the server that contains 1046 Unicode code points (whose UTF-8 representation is 1046 octets long).

Questions:

1. Is this indicating an intentional limit on the maximum size of outbound messages?
2. Can this limit be increased?

The subprotocol I'm speaking, [graphql-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.18/PROTOCOL.md), can involve messages whose size exceeds 1024 code points.

Details:
- websocat 1.9.0 from Homebrew
- terminal emulator: iTerm2 3.4.11
- shell: zsh 5.8 from /usr/bin/zsh
- OS: macOS 11.3
- architecture: arm64

**Comment by vi** [comment]
A Mac and 1024 bytes? Looks similar to #103 or #76.

You may want to try using `rlwrap websocat ...` or some `stty` workaround.

**Comment by spencerwilson** [comment]
Thanks for the quick pointer. You're probably right. I found a workaround (using something other than `websocat`) so I'll close this issue now.
