### ISSUE TITLE
Re-establish connection after websocket is closed

### ISSUE THREAD

**Issue by arabelaa** [vi/websocat#157]
We are proxying tcp connection to  websocket.
` websocat -b -E ws://host.docker.internal:8888/client tcp:127.0.0.1:5800`

I was wondering if there is an option that can re-establish the connection with tcp when the websocket is closed? 
I saw `autoreconnect` overlay but that just re-connects the websocket back. I also need to re-establish the connection tcp - websocket. 

Is there an option (overlay) to recreate the connection in case the websocket is closed?

Thanks

**Comment by vi** [comment]
Maybe you just want to run Websocat in a loop?

```
while true; do websocat -b -E ws://host.docker.internal:8888/client tcp:127.0.0.1:5800; done
```

If WebSocket close detection is not reliable, you can `--ping-interval` and `--ping-timeout`.

**Comment by arabelaa** [comment]
Indeed that can be an option. I was just wondering if there was an overlay/flag that I missed. 

Thanks.

**Comment by arabelaa** [comment]
is there a way to check if `EOF` was received and only then to redo the connection?
