### ISSUE TITLE
how to save only last received message

### ISSUE THREAD

**Issue by TonyStark** [vi/websocat#158]
`$ websocat -t "wss://........" > tmp`
it saves all message in `tmp` file
example: `$cat tmp`
```
AAA
BBB
CCC
DDD
```
But how to save only last Received message each time in `tmp` file not all message?

PS:Im using Linux

**Comment by vi** [comment]
Example:

```
websocat -nbu ws://127.0.0.1:1234/ foreachmsg:writefile:/tmp/file.txt
```

It won't allow sending messages to WebSocket, only receiving and saving them.

**Comment by vi** [comment]
Another command line to preserve ability to send WebSocket messages as well. This version would mangle binary message unfortunately.

```
stdbuf -o0 tr '\n' '\0' | /opt/websocat -t0 ws://127.0.0.1:1234/ - | xargs -0n1 strace -fe execve sh -c "printf '%s' \"\$0\" > /tmp/file.txt"
```

**Comment by TonyStark** [comment]
Thank you very much :)
