### ISSUE TITLE
Is there a way to keep websocat receiving content from named pipe?

### ISSUE THREAD

**Issue by UrNightmaree** [vi/websocat#179]
Is there a way to keep websocat receiving content from named pipe?

For example, I have a FIFO named `myfifo` in `/tmp` (`/tmp/myfifo`). I want it to always receiving content from pipe without reconnecting it.
```bash
while true; do
  websocat - wss://ws.ifelse.io --text < /tmp/myfifo
  # Don't disconnect after receiving content from pipe
done
```

**Comment by vi** [comment]
Maybe you want something like this:

    websocat --text autoreconnect:open-async:/tmp/myfifo - | websocat - wss://ws.ifelse.io --text

**Comment by UrNightmaree** [comment]
Okay, I will try it

**Comment by UrNightmaree** [comment]
`websocat` hangs after receiving second message from pipe

**Comment by UrNightmaree** [comment]
Nevermind, I'll use the method from issue #68. Anyway thanks for the help.
