### ISSUE TITLE
No http proxy support

### ISSUE THREAD

**Issue by colemar** [vi/websocat#185]
Websocat seemed very promising as a websocket client for Windows.
Unfortunately I need to tunnel through an http proxy with basic authentication, and websocat provides no options for this.

I mean like:
```
curl -v https://remote-websocket-server.xx/ \
  -H "Upgrade: websocket" \
  -H "Sec-WebSocket-Version: 13" \
  -H "Sec-WebSocket-Key: Z29yYWRkdQo=" \
  --proxy http://user:password@myproxy.xx:8080
```

**Comment by vi** [comment]
For now you can use external tool like `connect-proxy` to use HTTP proxy with Websocat:

https://github.com/vi/websocat/blob/74e5253d6f3b2eebcec91f73cf595fbc3694cb97/moreexamples.md#connect-to-a-websocket-using-http-proxy

**Comment by colemar** [comment]
This works (proxytunnel -e -z manages the TLS channel):
`websocat.exe -v -b - --ws-c-uri=ws://remhost.xx:4433/whatever/ ws-c:cmd:"proxytunnel.exe -e -z -p myproxy.xx:8080 -P proxyuser:password -d remhost.xx:4433"`

This does not work (websocat should manage the TLS channel):
`websocat.exe -v -b - --ws-c-uri=wss://remhost.xx:4433/whatever/ ws-c:cmd:"proxytunnel.exe -p myproxy.xx:8080 -P proxyuser:password -d remhost.xx:4433"`
It seems that websocat is attempting to speak websocket protocol without setting up the TLS channel.

**Comment by vi** [comment]
> websocat should manage the TLS channel

`--ws-c-uri` is only used for path and `Host: ` header. Scheme part is ignored.

You need to insert TLS overlay explicitly for this:

    websocat.exe -v -b - --ws-c-uri=wss://remhost.xx:4433/whatever/ ws-c:tls:cmd:"proxytunnel.exe -p myproxy.xx:8080 -P proxyuser:password -d remhost.xx:4433" --tls-domain=remhost.xx
