### ISSUE TITLE
How to respond automatically as a server.

### ISSUE THREAD

**Issue by nopnop2002** [vi/websocat#193]
Is there a way to automatically respond as a server?

Terminal 1
Start websocat as server.
```
$ websocat -s 0.0.0.0:8765
Listening on ws://0.0.0.0:8765/
```

Terminal 2
Start websocat as client.
```
$ websocat ws://192.168.10.46:8765
```

When I type hello in terminal 2, hello is displayed in terminal 1.
When I type ok in terminal 1, ok is displayed in terminal 2.

I want to automate the operation of Terminal 1.
In other words, when terminal 1 receives something, I want to automatically respond with OK.

I don't want to reply anything before terminal 1 receives something.
So I can't use the echo command pipe.
This will return OK as soon as the client connects.
```
$ echo "ok" | websocat -s 0.0.0.0:8765
Listening on ws://0.0.0.0:8765/
```

**Comment by nopnop2002** [comment]
I found.

```
$ websocat -E -t ws-listen:0.0.0.0:8765 literalreply:'OK'
```

**Comment by nopnop2002** [comment]
It turns out that it does not display the received data.

I want to see the received data.

```
$ websocat -E -t ws-listen:0.0.0.0:8765 literalreply:'OK'
```

**Comment by vi** [comment]
Does `websocat -E -t ws-listen:0.0.0.0:8765 log:literalreply:'OK'` suit your use case?

**Comment by nopnop2002** [comment]
Good!!
