### ISSUE TITLE
doesn't work with localhost, but ok with 127.0.0.1 (guessing related to IPv6)

### ISSUE THREAD

**Issue by halturin** [vi/websocat#194]
I got a weird issue. Tried to connect using 
`websocat ws://localhost:9090/ws`
and got this error:
```
websocat: WebSocketError: I/O failure
websocat: error running
```
if I change the hostname to the IP address it works well. 

my `/etc/hosts` has `localhost` records 
```
127.0.0.1 localhost
::1 localhost
```

`telnet` command works well with the `localhost` hostname
```
$ telnet localhost 9090
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

I guess it tried the IPv6 address, got `connection refused`, and exited.

**Comment by vi** [comment]
It is know "happy eyeballs" deficiency in Websocat 1.0: https://github.com/vi/websocat/issues/23#issuecomment-1001550993

**Comment by halturin** [comment]
Thanks for clarifying. It would be great to be mentioned in the README file.
