### ISSUE TITLE
Can websocat perform force resolve?

### ISSUE THREAD

**Issue by zmwmcfyy** [vi/websocat#198]
something like`websocat wss://test.com --resolve "test.com:1234:10.10.10.10"` would be very helpful

**Comment by vi** [comment]
You may want to use this command line:

   websocat -t - ws-c:tls:tcp:10.10.10.10:443 --ws-c-uri=wss://test.com/ --tls-domain test.com

I'm not sure what `1234` means in your sample.

**Comment by zmwmcfyy** [comment]
> You may want to use this command line:
> 
> ```
> websocat -t - ws-c:tls:tcp:10.10.10.10:443 --ws-c-uri=wss://test.com/ --tls-domain test.com
> ```
> 
> I'm not sure what `1234` means in your sample.

Just a remote port number. Thank you!
