### ISSUE TITLE
How to transfer text and binary data in one connection?

### ISSUE THREAD

**Issue by ssmmhh** [vi/websocat#20]
Thank you for your great tools. ^^

I want to use the Web SocketAPI. (via TCP)
ex) websocat tcp-l:127.0.0.1:4554 ws://123.456.789.012:8100/api/v1/fileupload 

The API works with three commands:

> 1. Deliver file information in json format.  {"action":"create", "filename":"test.png"} -> text mode
> 2. Deliver the actual contents of the file (test,png) -> binary mode
> 3. end point of the file. {"action":"stop"} ->text mode 

It determines the execution mode and allows only one to be used. (-t or -b)
Can I transfer binary data or text data while connected?
(I am using the Windows environment.)

**Comment by vi** [comment]
Unfortunately, sending both text and binary is currently not supported by current design of websocat.

There is also no obvious workaround. You can help by thinking and describing your opinious about how UX/workflow for mixing binary and text messages when forwarding from TCP would work. Note that status of being a text or binary message is only one part of the problem. Other part is how to find where contents of the file ends and the next text message begins.

What is that service with such API? Maybe there is some dedicated tool for it? Or it is the time to make such tool.

**Comment by nbanb** [comment]
Hi

Sure it's depend of the websocket server, but I had to handle this use case in nearly "pure bash" 

The idea is to use "--binary-prefix B" option of websocat and to stream binary file to upload in 512K chunk with `dd` (limitation of the websocket API I use), and after to prefix each chunk (`dd` binary block sent to the websoket) with the "--binary-prefix B" using `sed` command


I make it work the following way : 

```bash
$ # starting websocat as a background process with a TCP overlay I can connect from bash later
$ # the important websocat options I use here are : '--no-close --text --base64 --binary-prefix B'
$ SSL_CERT_FILE=/dev/shm/fbx-wsul-cacert websocat -H "X-Fbx-App-Auth: $_SESSION_TOKEN" --origin https://fbx.fbx.lan --protocol "chat, superchat" -vv --ping-interval 10 --no-close --text --base64 --binary-prefix B tcp-listen:127.0.0.1:2009 wss://fbx.fbx.lan/api/v12/ws/upload/ &
$  # saving websocat PID in $wspid variable for killing websocat later
$ wspid=$!   
$ # starting "my home made bash" input/output tcp client using file descriptor 3 (do not use fd 5 !) : 
$  exec 3<>/dev/tcp/127.0.0.1/2009 ; CR=$(echo -en "\r"); while read <&3; do echo -e "\r${REPLY//$CR/}"; done &
$ # sending TEXT (a json) to say the websocket server I will send a file (syntaxe is the one used by websocket server API) : 
$ echo  '{"action":"upload_start","request_id":"904003","size":"104857600","dirname":"L0ZCWDI0VC90ZXN0","filename":"myvm0.qcow2","force":"overwrite"}' >&3
{"action":"upload_start","success":true,"request_id":"904003"}  # API answer
$ # Now I will send 512K BINARY frames I cut from a file with 'dd' and I prefix each block with 'B' define in websocat option  '--binary-prefix B' 
$ dd if=/home/user/myvm0.qcow2 bs=512K | sed -e 's/^/B:/'>&3
...
{"action":"upload_data","success":true,"result":{"total_len":98453996,"complete":false},"request_id":"904003"} # API TEXT ANSWER from recieved BINARY frames
{"action":"upload_data","success":true,"result":{"total_len":98454104,"complete":false},"request_id":"904003"} # API TEXT ANSWER from recieved BINARY frames
{"action":"upload_data","success":true,"result":{"total_len":98454232,"complete":false},"request_id":"904003"} # API TEXT ANSWER from recieved BINARY frames
...
$ # now I will send TEXT again to this text websocket to tell the API upload is finished
$ echo "{\"action\":\"upload_finalize\",\"request_id\":904003}" >&3
{"action":"upload_finalize","success":true,"result":{"total_len":104856056,"complete":true},"request_id":904003}  # Text answer from API
$ # closing everything : 
$ exec 3>&-
$ kill $wspid
$ # at the end verify if  everything (process, fd...) is closed :  
$ jobs -l   # should answer nothing as it's the case here
$
```

I have to make a lot of test / debug to make it work so I hope this comment would help people who need to mix text and binary inside `websocat`, specially to upload files in binary chunk over a websocket API which recieved it's order command in text


@ssmmhh : enjoy !
@vi : in the end, it is possible (and nearly in 'pure' bash). Thanks for `websocat` tool 

Kind regards
nbanba

**Comment by vi** [comment]
> `dd if=/home/user/myvm0.qcow2 bs=512K | sed -e 's/^/B:/'`

Maybe something like `base64 -w$((512*1024*3/2))` is missing in the middle?

I see `--base64` option used on Websocat, but qcow data streamed directly (without base64 encoding); also `sed` operating on binary data instead of text.

**Comment by nbanb** [comment]
Dear @vi 
You're right ! I forget it and it had some impact on the .qcow2 file !

I was also required to grow up `websocat` buffer accordingly to the chunk size (512 bytes more than the chunk size), because I get this error: 
```bash
[WARN  websocat::line_peer] Splitting too long line of 786434 bytes because of buffer (-B option) is only 65536 bytes
[WARN  websocat::line_peer] Splitting too long line of 720898 bytes because of buffer (-B option) is only 65536 bytes
[WARN  websocat::line_peer] Splitting too long line of 655362 bytes because of buffer (-B option) is only 65536 bytes
[WARN  websocat::line_peer] Splitting too long line of 589826 bytes because of buffer (-B option) is only 65536 bytes
websocat: WebSocketError: I/O failure
```

in the end, here is what's WORKING and file is OK after transfer over websocket : 

```bash
$ SSL_CERT_FILE=/dev/shm/fbx-wsul-cacert websocat -H "X-Fbx-App-Auth: $_SESSION_TOKEN" --origin https://fbx.fbx.lan --protocol "chat, superchat" -v --ping-interval 10 --no-close --buffer-size $((512*1025)) --text --base64 --binary-prefix B tcp-listen:127.0.0.1:2009 wss://fbx.fbx.lan/api/v12/ws/upload &
$ wspid=$!   
$ exec 3<>/dev/tcp/127.0.0.1/2009 ; CR=$(echo -en "\r"); while read <&3; do echo -e "\r${REPLY//$CR/}"; done &
$ echo '{"action":"upload_start","request_id":"904010","size":"104857600","dirname":"L0ZCWDI0VC90ZXN0","filename":"myvm3.qcow2","force":"overwrite"}' >&3
{"action":"upload_start","success":true,"request_id":"904010"} # API ANSWER 
$ dd if=/home/user/myvm3.qcow2 bs=512K | base64 -w$((512*1024)) |sed -e 's/^/B/' >&3
{"action":"upload_data","success":true,"result":{"total_len":393216,"complete":false},"request_id":"904010"} # API ANSWER 
...
{"action":"upload_data","success":true,"result":{"total_len":104857600,"complete":false},"request_id":"904010"} # API ANSWER 
$ echo '{"action":"upload_finalize","request_id":904010}' >&3
{"action":"upload_finalize","success":true,"result":{"total_len":104857600,"complete":true},"request_id":904010} # API ANSWER
$ exec 3>&-
$ kill $wspid
```

And after upload over the websocket, I did control the file: 

```bash
$ # localy : 
$ sha512sum /home/user/myvm3.qcow2 
40dfbe657a4ece5db44b2578fab46e4280c94749ba82473ac2509a3b14ed1b45b8d48776665c70600fae7ea405f19acbad2e0719e09c151c2227f4a456a6b093  /home/user/myvm3.qcow2
$
$ # remotely : 
$ hash_fs_file src=/FBX24T/test/myvm3.qcow2 hash_type=sha512
40dfbe657a4ece5db44b2578fab46e4280c94749ba82473ac2509a3b14ed1b45b8d48776665c70600fae7ea405f19acbad2e0719e09c151c2227f4a456a6b093
```

So in my use case, it's working perfectly !
Thanks again @vi 
kind regards
nbanba

**Comment by nbanb** [comment]
Dear @vi 

After some new testing, the reverse (tagged base64 text frame in `--binary` mode) is working too

in documentation you wrote : 

> --base64-text
            [A] Encode incoming text WebSocket messages in one-line Base64. I don't know whether it can be ever useful,
            but it's for symmetry with `--base64`.

It's usefull if someone have trouble with `--text` mode and should use  `--binary`

This is also working : 

```bash
$ websocat -H "X-Fbx-App-Auth: $_SESSION_TOKEN" --origin https://fbx.fbx.lan --protocol "chat, superchat" -v --ping-interval 10 --no-close --buffer-size 524800 --binary --text-prefix T --base64-text tcp-listen:127.0.0.1:2009 wss://fbx.fbx.lan/api/v12/ws/upload &
$ exec 3<>/dev/tcp/127.0.0.1/2009 ; CR=$(echo -en "\r"); while read <&3; do echo -e "\r$(echo -n ${REPLY//$CR/}| sed -e 's/^T//'|base64 -d)"; done &
$ echo  T$(echo -n '{"action":"upload_start","request_id":"904011","size":"104857600","dirname":"L0ZCWDI0VC90ZXN0","filename":"myvm0.qcow2","force":"overwrite"}' | base64 -w0) >&3
$ dd if=/home/user/myvm0.qcow2 bs=512K status=progress >&3
$ echo T$(echo -n '{"action":"upload_finalize","request_id":904011}' | base64 -w0) >&3
```

kind regards
nbanba

**Comment by nbanb** [comment]
Dear @vi 


Really thanks for this really very usefull explanation of what `websocat` does internally in each situations (text / binary)  

> You expect one write to FD 3 to be converted to one WebSocket message, but that is not guranteed.

> Maybe you want --text instead of --binary - that would make data accumulate inside Websocat until a full line is available; also unglue the last chunk of the file being upload with upload_finalize message if they appear in one buffer.

I think that's why I get those kind of errors in binary mode after a certain quantity of datas transferred (between ~100MB and ~10GB of datas transferred), depending of websocat buffer size 
```bash
...
[ERROR websocat::ws_peer] Failed to decode user-supplised base64 buffer. Sending message as is.
[ERROR websocat::ws_peer] Invalid UTF-8 in a text WebSocket message. Sending lossy data. May be caused by unlucky buffer splits.
...
```

No errors in `--text` mode with `--base64` and `--binary-prefix B` and in this mode I did upload files until 100GB without troubles (did not test with bigger files)


I will have a look on `seqpacket:` and `lengthprefixed:` overlay to try to make my code more robust.

Big thanks again !
Kind regards
nbanba

**Comment by nbanb** [comment]
Dear @vi 

Just a small question : 
While transfering data (multiple gigabytes+ files) using `websocat` in mode text, sending tagged binary frames (`--binary-prefix B`) encoded in base64,  `websocat` is using 100% CPU at 1.1 to 1.5 Gbit/s data rate with 512K chunk sent using a Xeon 2698v4-3.6GHz 
I know it's quite an old CPU but it's also a strong CPU. I have similar results with Core i7 gen 9  and gen 11 (~5 GHz)
The server sending has a 4*10Gb/s network LAG and reading it's data on NVMe drives (more than 30Gb/s capable)  and the remote server (providing websocket API) is 10Gb/s connected and I'm writing on it storage which is a 4 SSD RAID5 array capable of minimum 5  Gb/s sustained throughput write (maybe 10Gb/s) 
So I think here websocat could be the bottleneck.
Is there a limitation (I cannot send bigger data chunk, 512K is a limit from remote server API) ? 
What do you think ?

NB: It's not really an issue but if there is an option which let me have the double throughput or more, it would be better

Thanks and kind regards
nbanba

**Comment by vi** [comment]
Base64 has overhead (it boosts traffic by 50%), `lengthprefixed:` mode may be faster.

If you are reading from stdin (e.g. from pipe), `--async-stdio` option may improve performance on Linux/Mac.

512K chunks may cause memory allocation pressure.

Websocat1 is designed for reasonable data transfer performance, but not super-optimised, especially if overlays or other tricky options are in use.
Maybe Websocat4 can attain higher speed (but some needed features may be missing).

Maybe compiling Websocat1 in other more (optimize for speed more, other memory allocator) can improve performance.

**Comment by nbanb** [comment]
Dear @vi 

Thanks for answer.
I'm already using `--base64` and I will try with `lengthprefix:` mode and to add `--async-stdio`.
I understand that 512K chunk can cause memory allocation pressure, which size could be recommended? (I can open a case at the API provider to try to modify this value if bigger chunks are needed).
During tests, the client servers didn't have memory troubles (several hundred of gigabytes were still unused) and if needed websocat can use more.
I did build websocat 1.13 myself with cargo, but I didn't modify anything, just build from source under debian12 amd64

For the moment I didn't try websocat4 and switching to websocat4 would be a big and sensitive change for users as they would have to install a new tool and there are some kinds of automata systems where these changes are painful.
I'm also thinking of a nearly 'pure bash' websocket data masking client, but for the moment websocat make a too nice and helpful job for I start this project...

Thanks again 
Kind regards 
nbanba

**Comment by vi** [comment]
`--async-stdio` is the first thing to try. If it is relevant, it may have the biggest impact.

> I understand that 512K chunk can cause memory allocation pressure, which size could be recommended?

I'm not sure. Maybe it is actually the more - the better. You may check e.g. 128K just in case to see if there is any difference.

> try with lengthprefix: mode

Note that you should switch to `--binary` mode back for this. Here is a simple example of `lengthprefixed:` usage:

    printf '\x00\x00\x00\x14BI am binary message\x00\x00\x00\x12TI am text message' | /opt/websocat lengthprefixed:- -b ws://127.0.0.1:1234 --async-stdio --binary-prefix=B --text-prefix=T

> For the moment I didn't try websocat4 and switching to websocat4 would be a big and sensitive change for users as they would have to install a new tool and there are some kinds of automata systems where these changes are painful.

This change should be postponed to when Websocat4 would be primary version (not soon) then.

**Comment by nbanb** [comment]
Dear @vi 

Thanks a lot for answer and benchmarking !
I will make some new tests to see if I get the same or which "optimization" could help.

First I'm gonna try `--async-stdio` but for that I need to review a massive part of the underlying read/write websocket engine of the library I maintien as it require I'm writing directly into websocat stdin/pipe and not into the tcp overlay provided by websocat option I'm currently using.

Second I will test `lengthprefixed:` mode using pure binary mode (sure using base64) as you suggest. 

Third, I will play with websocat buffer and binary data chunks size to see if there is any throughput difference.

Last, I 'm happy to constat that your first benchmarking test result with websocat1 is nearly the same as all tests I've made (so my code should not be the main part of the throughput limitation)

I will come back here with results...

Thanks again and kind regards 
@nbanb

**Comment by nbanb** [comment]
Dear @vi 

Thanks a lot again for your help + answer , etc...
First, I didn't achieve making websocat work (for my use case) without tcp overlay: `tcp-listen:${tcp_host}:${tcp_port}`
I did not achieve to send direct instructions/data to /proc/$websocat_pid/0 and to get back results on /proc/$websocat_pid/stdout + /proc/$websocat_pid/stderr file descriptors so I cannot use option `--async-stdio` from nearly 'pure bash' but using tcp-listen: overlay I'm able to send and recieve data using websocat from bash with a function like :
```bash
tcp_wscon () {
exec {fd0}<>/dev/tcp/${tcp_host}/${tcp_port}    # connect {fd} to tcp pipe

 while read <&${fd0}
        do
                wsreply=${REPLY//$CR/}
                echo ${wsreply} >/dev/shm/lastreply_$wspid
                echo ${wsreply} >>/dev/shm/allreply_$wspid
        done & 
#...
# sending command over websocket:
echo ${ul_param_object[$k]} >&${fd0}
# reply is in file /dev/shm/lastreply_$wspid
}
```

I still need more time to test `lengthprefix:` overlay option (mainly due to a not small part of code to rewrite) but I will come back here soon with results.

Last point, the 512 KB chunk size limitation (from remote API) had been removed by API provider and now I 'm able to send chunks from 64 KB to 1023 KB (1M minus 1KB) so I think I will be able to test websocat behavior/performance and CPU usage with different chunk size configuration.
To optimise bandwidth, maybe it could be nice that websocat-v1 could handle safely and without memory pressure the biggest possible chunks (up to 1M and/but today using a `websocat` buffer size bigger than (520~600)*1024K often resuls in a `websocat` IO error).

I'll come back here with next results,

Thanks again and merry Christmas !
Kind regards
nbanba

**Comment by vi** [comment]
> cannot use option `--async-stdio` ... but using `tcp-listen:`

`tcp-llisten:` should already avoid non-async stdio performance penalty.

There may be some minor speed up if you replace localhost TCP with UNIX or abstract socket.

**Comment by vi** [comment]
> pure bash

Why do you keep using hacky scripts instead of implementing it in using proper tools (with or without Websocat as a component)?

If it is a production setup with performance and security requirements then less flexible, more integrated solution is advised.

**Comment by vi** [comment]
Note that you may also benefit from adjusting TCP socket buffer sizes in the operating system, especially if CPU usage is not 100% (of a core), but speed gets limited anyway.
