### ISSUE TITLE
Feature Proposal: Add message framing to binary stream i/o

### ISSUE THREAD

**Issue by LatentLag** [vi/websocat#201]
Using websocat for streaming protocols works great but they must provide their own message framing. Some WebSocket usage relies on WebSocket message framing. To a extent websocat's existing feature works with option `--base64` however large and numerous messages take a toll on processing. The following is a proposal for discussion and implementation.

I propose adding a feature to provide in stream marking of messages and their size. The first byte giving a marker which indicates the WebSocket framing followed by a length of bytes. The framing mark will indicate if the message was marked as completed, not completed, or continuing to write a message payload. Following the marker the length of the data to read until the next framing mark. The length to be written as a varint, or some other well known format.

Using a short binary framing I want to reduce the overhead of passing through many messages with large payloads in a stream. This is in alternative to the existing base64 newline encoding of a message

**Comment by vi** [comment]
Do you mean something like a binary (more performant) analogue of Websocat's `--base64 --base64-text --binary-prefix --text-prefix` (i.e. a mode which allows to mix and match arbitrary text and binary messages with preserved boundaries and whitespace)?

**Comment by LatentLag** [comment]
In that direction, yes. The existing binary versions separate message on newline or nul char but all bytes are valid in my binary messages.

**Comment by LatentLag** [comment]
To add, `--binary-prefix` is not usable for larger messages that are greater than read buffer size and cannot be "replayed" (stored as a file and redirected to `stdin`) to another application. I may have to use a rather long prefix which is not performant.

**Comment by vi** [comment]
You can adjust buffer size with `-B` (unless you want the whole big file as one big WebSocket message).

Currently WebSocat assumes any WebSocket message can fit in memory (maybe multiple times).

**Comment by vi** [comment]
What other `websocat` features do you use?

If it's just `some_program | websocat -b ws://...` then maybe it would be simpler to create a dedicated, simpler tool for it?

**Comment by vi** [comment]
Implemented `lengthprefixed:` overlay - it allows 1 to 8 of big- or little-endian length bytes to denote message boundaries and works in both directions.

Is it what you need?

**Comment by LatentLag** [comment]
Thank you, this looks great.

**Comment by LatentLag** [comment]
Closing, thank you!
