### ISSUE TITLE
How do you get your own socket ID?

### ISSUE THREAD

**Issue by danwdart** [vi/websocat#202]
How would one get one's own socket ID of for example the nc process in the websocket -> nc -l example?

Thanks

**Comment by vi** [comment]
What do you mean by socket ID? A port?

`nc -l` is typically used with `-p` argument to set the port number. That port number can be used in Websocat to connect to the Netcat.

```
$ nc -lvp 1234
Listening on 0.0.0.0 1234
```

```
$ /opt/websocat -b - tcp:127.0.0.1:1234
```

```
Connection received on localhost 52780
```

**Comment by danwdart** [comment]
Perhaps this is a sub-protocol thing in which individual clients are assigned codes to refer to each other, used in Pusher and Socket.IO. Never mind, seems out of scope.
