### ISSUE TITLE
What do I do with the file?  Say 'websocat.aarch64-unknown-linux-musl' I downloaded, now what?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [vi/websocat#210]
What do I do with the file?  Say 'websocat.aarch64-unknown-linux-musl' I downloaded, now what?  I am trying to use the lgtv script that has a requirement for weboscat?

**Comment by vi** [comment]
For example, something like these steps:

1. `mv websocat.aarch64-unknown-linux-musl /opt/websocat`
2. `chmod +x /opt/websocat`
3. `PATH=$PATH:/opt lgtv ...`
