### ISSUE TITLE
provide library to construct pipeline for `Command` without running websocat as standalone process

### ISSUE THREAD

**Issue by poly000** [vi/websocat#215]
1. replace all `println!` to `writeln!` e.g.
2. helper function to parse & validate args as running from command line
3. helper function to validate options with Opt struct
4. accept two `Option<Stdio>`, and a ValidatedOpt (maybe)
5. pipe stdin, stdout

**Comment by vi** [comment]
What is your use case?

What `Command` do you mean? [`std::process::Command`](std::process::Command)?

Do you mean full Websocat functionality (UDP, overlays, multiplexing, UNIX sockets) or just basic client mode like `websocat wss://my.site/`?

**Comment by poly000** [comment]
> What is your use case?
pipe `fio`'s stdout to a websocket client

> What `Command` do you mean? `std::process::Command`?
sure
 
> Do you mean full Websocat functionality (UDP, overlays, multiplexing, UNIX sockets) or just basic client mode like `websocat wss://my.site/`?
basic client mode is enough for my use case

**Comment by vi** [comment]
Note: `rust-websocket` project (`websocket` crate) is semi-abandoned and depends on outdated dependency `hyper 0.10`.

You should try [tungstenite](https://docs.rs/tungstenite/latest/tungstenite/fn.accept.html) instead.
