### ISSUE TITLE
Specify server TLS certificate

### ISSUE THREAD

**Issue by WxNzEMof** [vi/websocat#221]
Is it possible to specify the server's certificate, like the `--cacert` option in cURL, or like the `--ca-certificate` option in wget?

I.e. if the server is using a self-signed certificate, and we have the certificate (public key) file, we would like to verify the peer against only that certificate so that we can connect to it securely.

Thanks!

**Comment by vi** [comment]
Try using `SSL_CERT_FILE` environment variable.

Note that you may need `openssl-probe` crate feature for this. Pre-built executables typically include this feature.

**Comment by WxNzEMof** [comment]
It works, thank you!
