### ISSUE TITLE
Specify TLS hostname separately from connect hostname

### ISSUE THREAD

**Issue by WxNzEMof** [vi/websocat#232]
Hi,

Is it possible to specify the address to connect to separately from the address that is verified against the server's TLS certificate?

Like `curl`'s `--resolve` or `--connect-to`?

Thanks!

**Comment by vi** [comment]
There is `--tls-domain` option for the case where you don't use convenient `wss://` URL, but compose the stack manually using overlays.

    websocat ... ws-c:tls:tcp:1.2.3.4:443 --tls-domain=check_tls_certificate_with_this.com --ws-c-uri=wss://whatever_goes_in_host_header.com/path

**Comment by WxNzEMof** [comment]
Ah, thank you! I missed the `--help=long` hint!
