### ISSUE TITLE
How do websocat know the other one reached EOF ?

### ISSUE THREAD

**Issue by AlwaysNoobCoder** [vi/websocat#235]
```
-E, --exit-on-eof                           Close a data transfer direction if the other one reached EOF
```

how do websocat know the other one reached EOF ?

**Comment by AlwaysNoobCoder** [comment]
@vi  maybe this is silly, but can you give some inputs ?

**Comment by vi** [comment]
Typically when `recv(3)` or `read(3)` syscall returns 0 bytes or maybe after receiving WebSocket close message.

By default (without `-E`) it waits for the other direction to also return 0 bytes before considering the connection as finished. With `-E` it drops possible future or pending data and closes the other direction immediately.

For example, in this invocation:

    websocat wss://ws.vi-server.org/mirror

there are two directions:

1. Reading from stdin and writing to a WebSocket
2. Reading from the WebSocket and writing to stdout

If you press Ctrl+D, you cause stdin to signal end-of-file, so it finishes the first direction. If WebSocket sends close message or drops the connection, it finishes the second direction.

**Comment by AlwaysNoobCoder** [comment]
@vi thanks! 
without `-E` , websocat command will not exit, even the server already closed the websocket session, this behaviour is a bit confusing for me.
