### ISSUE TITLE
Is there any way to print plain text of request and response when connecting to wss endpoint ?

### ISSUE THREAD

**Issue by AlwaysNoobCoder** [vi/websocat#238]
I can use wireshark + `export SSLKEYLOGFILE=~/.ssl-key.log` to decrypt packets for browser.

but don't know how to do with websocat.

**Comment by vi** [comment]
You can build WebSocket connector manually using overlays, then also use `log:` overlay for debug printing: https://github.com/vi/websocat/blob/master/moreexamples.md#at-http-and-websocket-protocol-level
