### ISSUE TITLE
Pkcs12 compatibility issues on OpenSSL 1.x.x

### ISSUE THREAD

**Issue by uuonda** [vi/websocat#239]
On OpenSSL 1.x.x this command from the docs generates pkcs12 file incompatible with websocat.
```
openssl pkcs12 -export -out output.pkcs12 -inkey key.pem -in cert.pem
```

The error message is not printed until after first incoming connection.
```
websocat: error::digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:355:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```
This happens because OpenSSL 1.x.x uses "legacy" RC2-40 algorithm. The fix is 

```
openssl pkcs12 -export -descert -out output.pkcs12 -inkey key.pem -in cert.pem
```

Hopefully that will save some time for someone.

**Comment by vi** [comment]
Maybe it's also why [I needed to update sample certificate](https://github.com/vi/websocat/commit/1c3c850289c78568faf2f1327a79b3e293f6263f) to test TLS?

**Comment by vi** [comment]
It quick test some TLS things without bothering to issue `openssl` commands or using actual CA during the development. For example, to connect to `wss://127.0.0.1` from a `https://` site in browser (by temporarily approving the test certificate). `ws://127.0.0.1` won't work, you need some TLS.

**Comment by vi** [comment]
I'll probably adjust the sample command line in the help and the document.

**Comment by liaoya** [comment]
> I'll probably adjust the sample command line in the help and the document.

Please update https://github.com/vi/websocat/blob/master/moreexamples.md

**Comment by vi** [comment]
Added `-descert` to `moreexamples.md`, though that session works for me as is as well with `OpenSSL 3.5.6`.
