### ISSUE TITLE
[v1.13.1] Release Date Request

### ISSUE THREAD

**Issue by AlperRehaYAZGAN** [vi/websocat#243]
Hi,

  I am using websocat right now and i need to hide basic auth creds with "WEBSOCAT_BASIC_AUTH" env value referenced closed issue https://github.com/vi/websocat/issues/240. This feature added 2 weeks ago and I kindly request to include it new version as soon as possible. Currently i am doing docker multistage clone-build and binary-copy-to-second-stage. But It would be great to make new release date close as possible. 

This could be not an issue but thanks for your all amazing works and product guys.

Sincerely.

**Comment by vi** [comment]
Why specifically a release is needed?
Maybe just point it to a commit you need?

**Comment by AlperRehaYAZGAN** [comment]
For our specific use case, we are using websocat in our development environment with pre-defined Dockerfiles. This setup ensures user dev ide (like gitpod) and stream some OS information to our servers. Currently we solve it in staticly Dockerfile CMD and username:password from explicitly format (which new process could see password with "ps aux"). But it would be a great to just inject as ENV value and then new processes could not access websocat password by just typing "ps aux".  
  
I requested this feature cause in Dockerfile we are writing multistage to build ENV supported version instead of "apk add websocat". But if you release with new version i will just reduce one stage and env value format that easy to manage. Its a presonal request actually 😅.  

>Yeah exact commit version clone and build from source code with Rust solves currently. Thanks for this amazing product.🔥
