### ISSUE TITLE
Feature request: Filter out whitespace from CLI

### ISSUE THREAD

**Issue by macce** [vi/websocat#251]
When using websocat as a command line tool to debug my own websocket services, I would like to be able to copy-paste my pretty printed JSON objects straight from my editor into the terminal.

Today this does not work in a convenient way. It is possible to run websocat with the `--null-terminated` option, and manually insert a NULL character. However, in many terminals this may be hard to achieve.

It would be very convenient to give a custom marker, eg. send:
```
##
{
  "command": "list",
  "args": [ 1, 2 ]
}
##
```

This should be combined with a command line option, such as `--symmetric-message-markers '##'`. When encountering that marker, the CLI would just read lines until it found the end marker, then sending the message. The outgoing linefeeds are not the problem, but that websocat sends line by line.

Apart from this, thanks for a powerful tool!

**Comment by vi** [comment]
Will simpler implementation of just using `\n\n` as a separator (i.e. empty line) instead of one `\n` or `\0` be enough?

**Comment by macce** [comment]
That would work perfectly well! Good idea. I just want to be able to copy-paste pretty-printed JSON messages from my editor and I don't need any empty lines within them.

**Comment by vi** [comment]
Implemented repeated byte separator in `websocat4` branch, you can try if it works for you.

The option is `--separator-n 2`, but not that many other options are not yet implemented. Some of them may be relatively quick to add, to aid testing.

**Comment by macce** [comment]
Works perfectly for me, just verified. Thanks a lot!
