### ISSUE TITLE
How can I pass an argument with websocat without using echo?

### ISSUE THREAD

**Issue by Oroborius** [vi/websocat#254]
I am trying to pass a string using websocat inside of [streamdeck-linux-gui](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui). Normally in kitty I could do something like this: `echo Calibrate | websocat ws://localhost:19190/` which would output and fire successfully. Now the issue is that in this program it executes echo a little bit differently and instead everything after echo gets passed as a string and websocat isn't triggered. Attempting to invoke websocat on it's own works but I cannot for the life of me figure out how to pass a string to it. Any help will be greatly appreciated! :-)

**Comment by vi** [comment]
Maybe you want `--preamble`?

**Comment by Oroborius** [comment]
This works! Thanks so much! :-)
