### ISSUE TITLE
Need help on compile

### ISSUE THREAD

**Issue by lovemyliwu** [vi/websocat#256]
Hello vi, I use https://github.com/lovemyliwu/home/blob/main/docker/build/websocat/Dockerfile to compile websocat, the process is success, but when I execute binary on centos 7, websocat crashed with `Segmentation fault`.

Please help me, thx!
![F2C6594E-9FB6-4f99-ACA0-5325482DA7B7](https://github.com/user-attachments/assets/7314d1a1-2da7-4b9e-ae7d-9529199cc33b)

**Comment by vi** [comment]
1. Does it still happen if you smaller buffer size, e.g. `-B 8192`?
2. Does a basic test like `./websocat wss://ws.vi-server.org/mirror` work?

**Comment by lovemyliwu** [comment]
Thanks for your reply.

I tried your segustion but still not work.  Lucky I found my build was not fully static link after compare to your release.

The problem was solved after modify Dockerfile to support rust static link.

If somebody interst what I do:

```diff
FROM rust:1.63.0-alpine3.15 as build
+ENV RUSTFLAGS='-Clink-arg=-s -Ctarget-feature=+crt-static'

# env prepare
-RUN apk add --no-cache git musl-dev pkgconfig openssl-dev
+RUN apk add --no-cache git musl-dev pkgconfig openssl-dev openssl-libs-static
+ENV OPENSSL_STATIC=1
+ENV OPENSSL_LIB_DIR=/usr/lib
+ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
```
