### ISSUE TITLE
Connection closed unexpected

### ISSUE THREAD

**Issue by lovemyliwu** [vi/websocat#257]
Hello vi.

If I use `--ping-interval 10 --ping-timeout 30` args, when the channel contention, websocat will `NOT` send ping request to server, but it still expected Pong answer, even though that will nerver happen.

At end websocat will close connection after ping timeout. 

This is not expected.

**Comment by vi** [comment]
Currently (in Websocat1) the algorithm is simple: the deadline timer is wind up at `now + ping_timeout`, each time `Pong` arrives (whether requested or not), it resets to `now _ ping_timeout`.

Ping sender and pong receiver components do not know about each other.

There is also a fix for pong replier (b93a7f61816fc399fa9fc73e91bcd1e927c1bf00), pending for Websocat v1.14.0. With the fix, it prioritizes replying to a ping over relaying more traffic, but it does not currently prioritize sending a ping over relaying more traffic. Maybe I'll fix it.

Websocat4 (redesigned version) does not currently send pings.

**Comment by vi** [comment]
Added outgoing ping prioritisation (commit 214de61843911f1e80286e37070700314ef859fa), but it doesn't seem to help much when socket send buffer is full.

**Comment by lovemyliwu** [comment]
Thanks for your fast response, I recommand to use simple strategy that aligns with intuition in Websocat 4.

If the channel is busy, just drop the ping request, but the pong receiver should know the situation and ignore timeout check.

**Comment by vi** [comment]
There will probably be the following additional options:

* `--ping-each-bytes n` - send ping each N outgoing bytes
* `--interpret-any-incoming-data-as-pong` - reset watchdog timer also on any incoming data
* `--interpret-any-outoing-data-as-pong` - reset watchdog times also on any outgoing data

Ability to send more outgoing data to a congested channel indicated that the channel is still alive.  
Also interleaving data with ping requests should cause a consistent stream of pong replies if the data is really flowing, not stuck.

**Comment by lovemyliwu** [comment]
For me,  check presense is enough. 😃 

---

I implemented ignore timeout check logic based on Websocat 1, If somebody interst, please check  b93a7f61816fc399fa9fc73e91bcd1e927c1bf00...11959c1cf217d31087eaf5d4a88bc5394158f208
