### ISSUE TITLE
Why do we send '\n' symbol after each text message? Is there any possibility to avoid that?

### ISSUE THREAD

**Issue by yeryomenkom** [vi/websocat#58]
@maxstreese

**Comment by vi** [comment]
Maybe you want binary mode `-b`?

Another influential options: `--no-line`, `--no-fixups`, `--linemode-strip-newlines`, `--strict`.

**Comment by yeryomenkom** [comment]
> Maybe you want binary mode -b?
No, I need to send text websocket frame.

> I may recommend some specific command line to use.
Thanks) I have a server that accepts websocket connections and somehow responds to the commands. The server is tested via integration test and works as expected. But, when I try to connect to that server via 'websocat', the issue with '\n' symbol occurs.

**Comment by yeryomenkom** [comment]
So, `--linemode-strip-newlines` does the job. 
Thank you for your help!

**Comment by yeryomenkom** [comment]
Weird, but I do not see that flag in `-help`. Do I miss something?

**Comment by vi** [comment]
`--help=full`?

Do you think this is important enough option to be moved to short help?

**Comment by yeryomenkom** [comment]
> Do you think this is important enough option to be moved to short help?

I think yes.
Honestly speaking, I would even change the default behavior for sending text frames.
Websocket protocol specifies nothing regarding the new line symbol in the end of text frame. So, at least for me, it was very confusing to realize that 'websocat' adds that symbol by default.

**Comment by vi** [comment]
> adds that symbol by default

More like "not removes the extraneous symbol by default". You can send one message without `\n` and without `--linemode-strip-newlines` as well:

    $ printf 'qwerty' | websocat  ws://...
    [WARN  websocat::line_peer] Sending possibly incomplete line.

**Comment by yeryomenkom** [comment]
> More like "not removes the extraneous symbol by default". Newline is typically present in user input. It gets inserted when one presses Enter.

I see. But in what case user may want to insert that symbol? I think user presses enter to send text frame. When I type `mkdir lol` and press Enter I expect that "lol" directory will be created. Not 'lol\n'.

> You can send one message without \n and without --linemode-strip-newlines as well:

Maybe I can, but I will never do)
