### ISSUE TITLE
strange behavior in "simple one-argument mode"

### ISSUE THREAD

**Issue by alkorsan** [vi/websocat#6]
I created a websocket server with websocat
```c
 websocat ws-l:127.0.0.1:8888 -
````
 
then I opened another websocat as client to connect to this server (using the simple one-argument mode)
```c
printf 'A\nB\nC\n' | websocat ws://127.0.0.1:8888
```
**the expected is :** the server should show my messages.
**the bug:** websocat server will buffer the messages he receives (wireshark shows that the server is receiving the messages and responding correctly with [ACK] ).
if I send a \n to the server then he will print all the old messages that he received before.

two-arguments mode works as expected like this `websocat ws://127.0.0.1:8888 -`

**Comment by alkorsan** [comment]
_the owner answered me in different places parts here I will merge all his answers writing with my bad english :/ from my head :_

websockets have two mode as the [RFC](https://tools.ietf.org/html/rfc6455) says: **text mode** or **binary mode**.

websocat have two modes a **simple mode** (used as a websocket client for ex.) and an **advanced mode** (when used as socat)
the simple mode example: 
```bash
websocat ws://echo.websocket.org/
```
the advanced mode example:
```bash
redirect TCP to a websocket
websocat tcp-l:0.0.0.0:8088 ws://echo.websocket.org
```

now remember that, in websocat the **simple mode** imply using **text mode**. and the **advanced mode** imply using **binary mode**.

since text mode imply using json, and since the standard json can never have a new line (only escaped new lines are accepted), then it doesn't matter to use `\n` as a terminator. websocat use new line as a terminator to delimit the end of every message.
so my issue is the expected behavior and this is not a bug but ignorance of my part.

and the good news is that the owner of websocat told me in other answers that he will add `-0 (null)` to separate messages instead of new lines `\n`, this will be good for a json that don't respect the standard or for servers demanding specific things...

**Comment by vi** [comment]
Advanced mode can fully simulate simple mode by enough additional options.

When `--binary` option be introduced, `websocat -b ws://...` would also use non-line and binary mode.

**Comment by alkorsan** [comment]
the solution to my problem was so easy and obvious after knowing (remembering :/) this:

> websocat ws://echo.websocket.org == websocat -tl - websocket://echo.websocket.org.

the solution was adding `--linemode-retain-newlines` to the simple mode, and now all the examples I had problems with now works, here are some:
create a server : 
```
websocat ws-l:127.0.0.1:8888 -
```
connect with the client and send some data:
```
printf 'A\nB\nC\n' | websocat --linemode-retain-newlines ws://127.0.0.1:8888
```
now the server will show :
```
A
B
C
```

an other problem I had is using websocat easy mode **interactively**:
create the server like above.
now use the websocat client to interact interactively with the server like this
```
websocat --linemode-retain-newlines ws://127.0.0.1:8888
```

every thing you write from the client will appear in the server console, good.

is it possible to add internally `--linemode-retain-newlines` to the simple mode? because a lot of things stop working without it

now for me I learned a lot of things from this days discussions, but new comers the first thing will test is this `websocat ws://127.0.0.1:8888`
and they will expect to be working interactively like all the other websocket solutions, but it is not the case , now the behavior is intimidating, nothing happen the server don t show the messages and the client don t tell you about any error, so the first thing will think a newcomer is that websocat don t even do a simple task like interactively working with server.

does including  --linemode-retain-newlines in the simple mode breaks something, or it s easy to implement? thank you

**Comment by vi** [comment]
It may become the default, with `--linemode-remove-newlines` options instead.

**Comment by vi** [comment]
Looks like the problem is Windows-specific (or more precisely `threadedstdio:`-specific). I see 

```
$ websocat ws-l:127.0.0.1:8889 -
Warning: replies on stdio get directed at random connected client
ABC<cursor here>
```

If I try it on Linux.

Anyway, the future simple server mode `websocat -s 8888` would be line-mode by default, and linemode auto-insertes `\n` regardless of it being present in the message.

**Comment by alkorsan** [comment]
now it works better :+1:  , the server now shows the messages (without `\n`). so one at less know that it is working but it needs a `\n` ; so he will go to the short description to see if there is a way to retain the `\n` and he will find it big and beautifully clear `--linemode-retain-newlines`.

the client:
```bash
$ printf 'A\nB\nC\n' | websocat ws://127.0.0.1:8888        

```
the server:
```bash
$ websocat ws-l:127.0.0.1:8888 -
Warning: replies on stdio get directed at random connected client
ABC
```

**Comment by vi** [comment]
There are two complementary counterparts that should work well together

_ | Simple | Advanced
--- | -- | --
Server | `websocat -s 127.0.0.1:8888` | `websocat -b ws-l:127.0.0.1:8888`
Client | `websocat ws://127.0.0.1:8888/` | `websocat  -b - ws://127.0.0.1:8888`

Simple client + simple server should be in one mode and feel nicely.
Advanced client + advanced server happens to work nicely as well, but it's less important.
Simple client + advanced server is allowed to feel weird / require some adjustments on server part to look OK.

Anyway, current defaults are not adjusted yet. Re-check how it feels in future.
