### ISSUE TITLE
--line option need a better description

### ISSUE THREAD

**Issue by alkorsan** [vi/websocat#7]
in an attempt  to understand what `--line` do, my conclusion was that:
`--linemode-retain-newlines` only tells to `--line` don't remove the new lines that you remove secretly, because `--line` is removing every `\n` that it found.

the description in the help doesn't tell you it will remove `\n`. `--line` short description should contain i think this : `\n` will be removed and if you want to preserve them use `--linemode-retain-newlines`.

**Comment by vi** [comment]
Note: `--line` (`-l`) option itself has gone. Now there is `--no-line`.

Linemode is now automatically inserted when websocat is set to text mode and first and second addresses differ in their stream-oriented vs message-oriented status.

**Comment by alkorsan** [comment]
oh good changes, thank you
