### ISSUE TITLE
[Question] Keep connection open in the background.

### ISSUE THREAD

**Issue by mygizli04** [vi/websocat#94]
So, i want `websocat` open in the background, listening to tcp connections, which accepts requests i make with `nc`

So:
Main script ---> Activates background script ---> Background script opens `websocat` and listens in the background ---> Main script uses nc to give commands for `websocat` to send ---> `websocat` sends the command ---> Connection doesn't close and a new message can be sent any time with the current connection.

or more preferably:
Main script ---> Activates `websocat` in the background ---> Messages can be sent and connection never closes

**Comment by vi** [comment]
Do you want something like [this](https://github.com/vi/websocat/blob/master/moreexamples.md#persistent-client-connection)?

**Comment by mygizli04** [comment]
Yes that's perfect! However i couldn't get it to work, because basically when the websocket i'm trying to open a connection to responds BEFORE i send anything, it breaks. For the echo server it works fine because i'm not getting any data before i send anything, but when the server sends anything before i do i cannot send anything, and whenever i try to connect to the tcp server i get the first message sent again

**Comment by mygizli04** [comment]
Oh i didn’t realise this issue was still open, well it’s solved.
